name: CI

on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "**.zig"
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "**.zig"
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [
        ]
    runs-on: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
          self-hosted,
    ]
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Build test executables
        run: zig build all_tests -Dci --verbose
